### ISSUE TITLE
你好，请问template的批量获取主机的正则表达式怎么写

### ISSUE THREAD

**Issue by 54ebb** [masato25/grafana-openfalcon-datasource#1]
我按http://book.open-falcon.org/zh/dev/support_grafana.html，在query中写.+，但是图中一个主机的metric也没有？

**Comment by masato25** [comment]
HI 54ebb, 歡迎你的詢問, 我剛剛查詢了一下, 應該是因為dashboard module 那邊我們實做的支援正規表達的code遺漏了PR. 你可以參考我們這裡的實作,手動先加入:

https://github.com/Cepave/dashboard/blob/develop/rrd/model/endpoint.py#L32
https://github.com/Cepave/dashboard/blob/develop/rrd/view/api.py#L90

謝謝

**Comment by 54ebb** [comment]
我现在已经测试了template的正则功能（falcon版本是0.1），比如在query栏我输入im（还是在grafana dashboard的template页面），下面的Preview of values会显示出匹配到的3台主机的名字；但是输入时不用写多余的正则符号，并且最少需要2个字母。
1、功能上算是可以用了，不过想确认一下是否是这样？
2、你贴的是falcon的dashboard组件代码，应该和我这个问题没关系吧？我记得grafana访问的是falcon的query组件。
并且我diff了那2个文件，和falcon 0.1 release对比：发现你的endpoint.py多了一个search函数，api.py不同的内容相对多一些，下面是falcon 0.1 release相应文件的地址：
[https://github.com/open-falcon/dashboard/blob/35dbee7bc06d294a32ecba18a62395e320dcfb8a/rrd/model/endpoint.py](https://github.com/open-falcon/dashboard/blob/35dbee7bc06d294a32ecba18a62395e320dcfb8a/rrd/model/endpoint.py)
[https://github.com/open-falcon/dashboard/blob/35dbee7bc06d294a32ecba18a62395e320dcfb8a/rrd/view/api.py](https://github.com/open-falcon/dashboard/blob/35dbee7bc06d294a32ecba18a62395e320dcfb8a/rrd/view/api.py)

**Comment by masato25** [comment]
在open-falcon中的query 會去詢問dashboard取得endpoint list, 官方 falcon 0.1 release 的作法是使用 mysql 的 `like` 語法, 也就是只支援"關鍵字" (例如: docker , 可以找到 "docker-agent", "docker-agent") 查詢, 如果你想要使用 正規表達式批配查詢的話, dashboard就需要有相對應的實做 , 我們這邊dashboard後端的實作只是將 like的查詢改作使用myql的regexp的查詢.
https://github.com/Cepave/dashboard/blob/develop/rrd/model/endpoint.py#L41

當get 參數中帶有  `regex_query=1` ,  後端會自動改用正規表達式的批配查詢. 
https://github.com/Cepave/dashboard/blob/develop/rrd/view/api.py#L76

grafana-openfalcon-datasource會自動帶入`regex_query=1` , 因為這個api是前後相容的, 所以即使你使用的版本中沒有 `Endpoint.search_regexp` 的實做也沒關係, 它會使用官方的`Endpoint.search`
https://github.com/open-falcon/dashboard/blob/35dbee7bc06d294a32ecba18a62395e320dcfb8a/rrd/model/endpoint.py#L15
如果你有需要正規表達式的需求可以嘗試將我們的dashboard的改動加入你正在使用的dashboard module中, 如果關鍵字查詢已經可以符合你的需求, 採用現有官方的dashboard就可以使用了

**Comment by 54ebb** [comment]
谢谢解答，很详细，这次我明白了

**Comment by masato25** [comment]
謝謝提問
