### ISSUE TITLE
您好：无法使用alias之类的Funcs

### ISSUE THREAD

**Issue by xianzi25** [masato25/grafana-openfalcon-datasource#2]
选择相应的Metrics之后，无法继续选择funcs，例如alias。不知我还要提供什么信息？

Grafana 3.1.0版本。还需要其他信息么？请指点，谢谢！

**Comment by masato25** [comment]
HI xianzi25
你說的funcs (ex. alias) 指的是graphite 提供的功能吧,
這個plugin大致上是基於graphite-grafana-datasource為基底修改的, 那些func是 graphite 本身這個db有提供的對應的實作,前端只是支援讓使用者可以設定要做什麼運算,  目前 open-falcon 的 query / rrdlite (graph) 並沒有提供這方面的運算支援, 所以這邊我是手動先將func先隱藏了, 因為就算顯示出來實際上後端沒實作也是無法使用的.

**Comment by masato25** [comment]
謝謝提問

**Comment by readilychen** [comment]
这个能力感觉挺有用的,可以大大提升提高可读性。后续是否能支持？

**Comment by readilychen** [comment]
> HI xianzi25
> 你說的funcs (ex. alias) 指的是graphite 提供的功能,
> 這個plugin大致上是基於graphite-grafana-datasource為基底修改的, 那些func是 graphite 本身這個db有提供的對應的實作,前端只是支援讓使用者可以設定要做什麼運算, 目前 open-falcon 的 query / rrdlite (graph) 並沒有提供這方面的運算支援, 原則上我有手動先將func先隱藏了, 如果顯示出來也無法使用,因為實際上open-falocn後端沒實作對應的運算功能.

这个能力感觉挺有用的,可以大大提升提高可读性。后续是否能支持？
