### ISSUE TITLE
query 大写字母无法识别

### ISSUE THREAD

**Issue by jtsky000** [masato25/grafana-openfalcon-datasource#3]
@masato25 ，帮助看一下下面的问题？
![image](https://cloud.githubusercontent.com/assets/6426223/18374399/1b9ac0c4-767f-11e6-9a75-5125a00e1381.png)

**Comment by zidanetang** [comment]
请问这个问题解决了么

**Comment by masato25** [comment]
抱歉 沒注意到有提問, 請問可以請你貼上更多一點說明嗎？
例如說 點選 "trigger edit mode" 之後顯示的文字是？
然後你預期可以達到的 結果是？ ex. 10.123.255.243.switch.puUtilzation.select.metric嗎？

這樣可以方便我解決問題 謝謝

**Comment by zidanetang** [comment]
#后面如果紧随大写字母的话，是无法识别，大写字母变成unfined,
另外，如果
![qq 20161115145435](https://cloud.githubusercontent.com/assets/18366662/20296025/7561ddf6-ab43-11e6-99c1-8b9b4bd682d8.png)
这样填写的话，这个主机也是不出图的

**Comment by zidanetang** [comment]
![qq 20161115145609](https://cloud.githubusercontent.com/assets/18366662/20296060/ae9f57ce-ab43-11e6-93bd-c2755f09651f.png)补充下大写字母的截图

**Comment by masato25** [comment]
![spectacle j22934](https://cloud.githubusercontent.com/assets/4387822/20296635/f4577528-ab46-11e6-9a2d-0c0aa41e8d47.png)

在我手邊的機器測試大寫 和 ip#metric 似乎沒有問題. 請問你部屬的 open-falcon query是哪個版本的？

**Comment by zidanetang** [comment]
query的版本是1.4.3 ea558f8
grafana的版本是Version 3.1.1 (commit: a4d2708)

**Comment by fxltsbl3855** [comment]
我这边也有这个问题，metrics 如果大写，上面就会出现undefined，
grafana版本：1.5.3 （安装包：go1.5.3.linux-amd64.tar.gz）
open-falcon版本：v0.1.0 （安装包：of-release-v0.1.0.tar.gz）
query版本：ea558f8

**Comment by fxltsbl3855** [comment]
![image](https://cloud.githubusercontent.com/assets/8154045/20704063/0067fe38-b659-11e6-93c6-f810af944a18.png)

**Comment by xiaoqiang0** [comment]
支持，期望解决下.

**Comment by masato25** [comment]
已發布修復版本在 master 更新套件就可以了 :)
![issue_fixed](https://cloud.githubusercontent.com/assets/4387822/20714828/370e88f6-b688-11e6-934a-6bdacb9f3d12.png)

**Comment by fxltsbl3855** [comment]
@masato25 是在grafana上更新一下falcon的插件就可以了吗？

**Comment by lemon9921010** [comment]
@masato25 grafana-openfalcon-datasource 已更新最新的代码，还是这个问题呀

**Comment by masato25** [comment]
以下是更新步驟, 應該是可以work的.可以試試看嗎？
```
➜  cd $GRAFAN_PAHT/grafana/grafana-3.1.1-1470047149/bin
➜  cd data/plugins 
➜  rm -rf grafana-openfalcon-datasource 
➜  git clone https://github.com/masato25/grafana-openfalcon-datasource
Cloning into 'grafana-openfalcon-datasource'...
remote: Counting objects: 85, done.
remote: Total 85 (delta 0), reused 0 (delta 0), pack-reused 85
Unpacking objects: 100% (85/85), done.
➜  cd ../../
➜  ./grafana-server
```
如果仍然不行 你可以確認一下裡面的 https://github.com/masato25/grafana-openfalcon-datasource/commit/e230d2b6d19d7e3b73762da353999b754786d13b file  是不是把相對應會產生問題的code註解掉了

**Comment by lemon9921010** [comment]
这样操作，更新代码后报
![image](https://cloud.githubusercontent.com/assets/18395169/20745908/57d4ce38-b71e-11e6-95ff-a05d5cf949d7.png)
@masato25 谢谢

**Comment by fxltsbl3855** [comment]
多谢楼主，我这边已经ok；我首先用grafana-cli plugins install xxx  来更新插件，还是没成功；
最后我是直接把ddatasource.js中的那句话注释掉了；
不知道grafana怎么彻底删除原来的插件，然后再重新安装，或者能有完善的更新方式。
感谢楼主

**Comment by masato25** [comment]
我這個repo是 非官方的repo.  會送到 grafana官方的repo 使用的是 https://github.com/hitripod/grafana-openfalcon-datasource . 我這個修正目前不會直接同步更新到 grafana 上所以沒辦法直接使用它們的cli更新.

我目前現在手邊的grafana 是採用tar.gz檔 下載的(http://grafana.org/download/). 印象中好像它抓plugin 的file path位址好像不同, 它會在 /var/lib/grafana/plugins/  or $Grafana/public/app/plugins/datasource  下載產生plugin檔案位置路徑的樣子. 因為我是tar.gz版本 它在啟動的時候會在我的 $Grafana/bin 目錄下產生 $Grafana/data/plugins 目錄 我的作法是使用這裡的 plugin 位置 也就是上面的更新步驟.

反正就是將以下路徑的 `grafana-openfalcon-datasource` 文件夾刪除, 然後在clone我這個repo的版本應該就可以運行了
*  /var/lib/grafana/plugins/
*  $Grafana/public/app/plugins/datasource 
*  $Grafana/data/plugins

**Comment by masato25** [comment]
已解決 closed
